# -*- coding: utf-8 -*-
from odoo import api, fields, models
from odoo.exceptions import Warning
from random import randint                      #import 'random' module / generates random 5 digit number

class Student(models.Model) :
    _name = 'student.user'
    _description = 'Student'
    student_number = fields.Char('Student Number', compute='compute_stu_num', store=True)
    first_name = fields.Char('First Name', required=True)
    last_name = fields.Char('Last Name', required=True)
    image = fields.Binary('Cover')
    name = fields.Char('Name', compute='computer_name')
    user_id = fields.Many2one('res.users', string='User', readonly=True, states={'draft': [('readonly', False)]}, default=lambda self: self.env.uid)
    email = fields.Char('Email Address', compute = 'compute_email', store=True)


    #Relationships
    program_student_id = fields.Many2one('program.course', string='Program')
    result_student_id = fields.One2many('result.module', 'student_result_id', string='Result')
    transcript_student_id = fields. Many2one('transcript.student', compute='compute_transcript', inverse='transcript_inverse', string='Transcript_student_id')
    transcript_student_ids = fields.One2many('transcript.student', 'student_transcript_id', string='Transcript_student_ids')

    #Function to display student numbers instead of ......
    @api.depends('student_number')
    def computer_name(self):
        for rec in self:
            rec.name = rec.student_number

    @api.depends('student_number')
    def compute_email(self):
        for rec in self:
            rec.email = str(rec.student_number) + '@cwc.ac.za'
            email = rec.email


    #Function to add 5 random digits to the end of the student number generated by the next function
    @api.multi
    def five_digits(self, n):
        range_start = 10**(n-1)
        range_end = (10**n)-1
        return randint (range_start, range_end)


    #Function to generate 3 digit student number based on first letter of first name
    @api.depends('first_name')
    def compute_stu_num(self):
        range_1 = ['A', 'B', 'C', 'D', 'E']
        range_2 = ['F', 'G', 'H', 'I', 'J']
        range_3 = ['K', 'L', 'M', 'N', 'O']
        range_4 = ['P', 'Q', 'R', 'S', 'T']
        set_1 = '200'
        set_2 = '211'
        set_3 = '222'
        set_4 = '233'
        set_5 = '244'
        for rec in self:
            namestr = str(rec.first_name)
            nameupper = namestr.upper()
            if nameupper[0] in range_1[0:4]:
                student_number = set_1 + str(self.five_digits(5))
            elif nameupper[0] in range_2[0:4]:
                student_number = set_2 + str(self.five_digits(5))
            elif nameupper[0] in range_3[0:4]:
                student_number = set_3 + str(self.five_digits(5))
            elif nameupper[0] in range_4[0:4]:
                student_number = set_4 + str(self.five_digits(5))
            else:
                student_number = set_5 + str(self.five_digits(5))

            rec.student_number = student_number
            return rec.student_number

    #Function that hmm....
    @api.one
    @api.depends('transcript_student_ids')
    def compute_transcript(self):
        if len(self.transcript_student_ids) > 0:
            self.transcript_student_id = self.transcript_student_ids[0]
    #Function that hmm....
    @api.one
    def transcript_inverse(self):
        if len(self.transcript_student_ids) > 0:
            # delete previous reference
            asset = self.env['transcript.student'].browse(self.transcript_student_ids[0].id)
            asset.student_transcript_id = False
        # set new reference
        self.transcript_student_id.student_transcript_id = self

    #Function to create and store student users
    @api.multi
    def add_student(self):
        new_user = self.env['res.users'].create({
            'name':self.first_name,
            'login':self.student_number,
            'new_password':self.student_number,
        })
        student_group_security = self.env['res.groups'].search([('name', '=', 'Student')])
        new_user.groups_id = student_group_security
